# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schwitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Schwitter.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='No_img.jpg', upload_to='profile_images'),
        ),
    ]
