# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schwitter', '0002_auto_20180322_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(related_name='_userprofile_friends_+', to='Schwitter.UserProfile'),
        ),
    ]
