# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schwitter', '0003_auto_20180322_2029'),
        ('Schwitter', '0003_auto_20180323_1224'),
    ]

    operations = [
    ]
