# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schwitter', '0004_merge_20180323_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(to='Schwitter.UserProfile'),
        ),
    ]
