# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schwitter', '0004_merge_20180323_1532'),
        ('Schwitter', '0005_auto_20180323_1442'),
    ]

    operations = [
    ]
