# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schwitter', '0006_merge_20180323_1611'),
        ('Schwitter', '0006_merge_20180323_1608'),
    ]

    operations = [
    ]
