# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schwitter', '0007_merge_20180327_1526'),
        ('Schwitter', '0006_merge_20180323_1556'),
    ]

    operations = [
    ]
